version: "3"

services:
  dynamodb:
    build: ./dynamodb-local
    image: md2/dynamodb-local
    command: -jar DynamoDBLocal.jar -dbPath ./data -sharedDb
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb

volumes:
  dynamodb-data:
