AWSTemplateFormatVersion: 2010-09-09
Description: S3 and CloudFront for static website hosting (OAI Available)

#--------------------------------------------------------------------------------
# Parameters
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
#--------------------------------------------------------------------------------
Parameters:
  ServiceName:
    Type: String
    Default: mt-sample
  Env:
    Type: String
    Default: dev
  ApiStage:
    Type: String
    Default: ""

#--------------------------------------------------------------------------------
# Conditions
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html
#--------------------------------------------------------------------------------
Conditions:
  CreateApiOrigin: !Not
    - !Equals [!Ref ApiStage, ""]

#--------------------------------------------------------------------------------
# Resources
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
#--------------------------------------------------------------------------------
Resources:
  # ----------------------------------------#
  # S3 Bucket
  # ----------------------------------------#
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ServiceName}-${Env}-react-app"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId

  # ----------------------------------------#
  # CloudFront
  # ----------------------------------------#
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: !Sub "S3Origin-${S3Bucket}"
            DomainName: !GetAtt S3Bucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
          - !If
            - CreateApiOrigin
            - Id: "ApiGatewayOrigin"
              DomainName: !Sub "{{resolve:ssm:/${ServiceName}/${ApiStage}/apigw/domain}}"
              CustomOriginConfig:
                OriginProtocolPolicy: "https-only"
                OriginSSLProtocols:
                  - "TLSv1.2"
            - !Ref AWS::NoValue
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: !Sub "S3Origin-${S3Bucket}"
          # CachingDisabled
          # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
        CacheBehaviors:
          - !If
            - CreateApiOrigin
            - PathPattern: !Sub "/${ApiStage}/*"
              TargetOriginId: "ApiGatewayOrigin"
              ViewerProtocolPolicy: redirect-to-https
              ForwardedValues:
                Headers:
                  - "Authorization"
                QueryString: true
              DefaultTTL: 2
              MaxTTL: 600
              MinTTL: 2
              AllowedMethods:
                - "GET"
                - "HEAD"
                - "OPTIONS"
                - "PUT"
                - "POST"
                - "PATCH"
                - "DELETE"
            - !Ref AWS::NoValue
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 10
            ResponseCode: 200
            ResponsePagePath: /
        HttpVersion: http2
        Enabled: true

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "access-identity-${S3Bucket}"
