version: 0.2
  phases:
    install:
      runtime-versions:
        nodejs: 12
      commands:
        - npm ci
    pre_build:
      commands:
        - touch .env
        - echo REACT_APP_API_ENDPOINT=project_env:${api_endpoint} >> .env
        - cat .env
    build:
      commands:
        - npm run build
  artifacts:
    files:
      - '**/*'
    base-directory: build
