version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd ./react/sample-app
      - npm ci
  pre_build:
    commands:
      - cd ./react/sample-app
      - touch .env
      - echo REACT_APP_API_ENDPOINT=project_env:${api_endpoint} >> .env
      - cat .env
  build:
    commands:
      - cd ./react/sample-app
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: ./react/sample-app/build
