service: mt-sample

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${opt:profile, self:custom.defaultProfile}
  region: us-west-2
  stackName: ${self:service}-${self:provider.stage}-serverless
  apiName: ${self:service}-${self:provider.stage}-api
  endpointType: REGIONAL
  logRetentionInDays: 30
  versionFunctions: false
  timeout: 30
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-lambda-deployment
    serverSideEncryption: AES256
  iam:
    role: myDefaultRole

#--------------------------------------------------------------------------------
# packaging
# https://www.serverless.com/framework/docs/providers/aws/guide/packaging/
#--------------------------------------------------------------------------------
package:
  individually: true

#--------------------------------------------------------------------------------
# variables
# https://www.serverless.com/framework/docs/providers/aws/guide/variables/
#--------------------------------------------------------------------------------
custom:
  defaultStage: dev
  defaultProfile: default
  # VPC
  vpcId: ${ssm:vpc}
  subnetA: ${ssm:private-subnet-a}
  subnetB: ${ssm:private-subnet-b}
  # Security Group
  lambdaSecurityGroup: ${ssm:security-group-for-lambda}
  # RDS
  rdsHost: ${ssm:/${self:service}${self:provider.stage}/rds/host}
  rdsUser: ${ssm:/${self:service}${self:provider.stage}/rds/user}
  rdsPassword: ${ssm:/${self:service}${self:provider.stage}/rds/password}
  rdsDatabase: ${ssm:/${self:service}${self:provider.stage}/rds/database}
  # DynamoDB
  dynamodbTable: ${ssm:/${self:service}${self:provider.stage}/dynamodb/table}

#--------------------------------------------------------------------------------
# layers
# https://www.serverless.com/framework/docs/providers/aws/guide/layers/
#--------------------------------------------------------------------------------
layers:
  Requirements:
    package:
      artifact: layers/artifact/requirements.zip
    compatibleRuntimes:
      - python3.8
    retain: false
  MtSampleCommon:
    package:
      artifact: layers/artifact/mt_sample_common.zip
    compatibleRuntimes:
      - python3.8
    retain: false

#--------------------------------------------------------------------------------
# functions
# https://www.serverless.com/framework/docs/providers/aws/guide/functions/
#--------------------------------------------------------------------------------
functions:
  fetch-openbd-summary:
    handler: main.handler
    package:
      artifact: functions/artifact/fetch_openbd_summary.zip
    description: ISBNをもとにopenBD APIから取得した書籍情報のsummaryを返す
    layers:
      - !Ref RequirementsLambdaLayer
      - !Ref MtSampleCommonLambdaLayer
    events:
      - http:
          path: /fetch/{isbn}
          method: get
          cors: true
  save-openbd-to-ddb:
    handler: main.handler
    package:
      artifact: functions/artifact/save_openbd_to_ddb.zip
    description: ISBNをもとにopenBD APIから取得した書籍情報のsummaryをDynamoDBに保存する
    layers:
      - !Ref RequirementsLambdaLayer
      - !Ref MtSampleCommonLambdaLayer
    environment:
      DYNAMODB_TABLE: ${self:custom.dynamodbTable}
    events:
      - http:
          path: /save-openbd/{isbn}
          method: put
          cors: true
  save-gbooks-to-ddb:
    handler: main.handler
    package:
      artifact: functions/artifact/save_gbooks_to_ddb.zip
    description: ISBNをもとにGoogle Books APIから取得した書籍情報のvolumeInfoをDynamoDBに保存する
    layers:
      - !Ref RequirementsLambdaLayer
      - !Ref MtSampleCommonLambdaLayer
    environment:
      DYNAMODB_TABLE: ${self:custom.dynamodbTable}
    events:
      - http:
          path: /save-gbooks/{isbn}
          method: put
          cors: true
  save-book-to-rds:
    handler: main.handler
    package:
      artifact: functions/artifact/save_book_to_rds.zip
    description: ISBNをもとにDynamoDBに保存されている書籍情報を取得・整形してRDSへ保存する
    layers:
      - !Ref RequirementsLambdaLayer
      - !Ref MtSampleCommonLambdaLayer
    environment:
      RDS_HOST: ${self:custom.rdsHost}
      RDS_USER: ${self:custom.rdsUser}
      RDS_PASSWORD: ${self:custom.rdsPassword}
      RDS_DATABASE: ${self:custom.rdsDatabase}
      DYNAMODB_TABLE: ${self:custom.dynamodbTable}
    vpc:
      securityGroupIds:
        - ${self:custom.lambdaSecurityGroup}
      subnetIds:
        - ${self:custom.subnetA}
        - ${self:custom.subnetB}
  invoke-save-book:
    handler: main.handler
    package:
      artifact: functions/artifact/invoke_save_book.zip
    description: ISBNをもとにsave-book-to-rdsを呼び出す
    layers:
      - !Ref RequirementsLambdaLayer
      - !Ref MtSampleCommonLambdaLayer
    environment:
      CHILD_FUNCTION_NAME: ${self:service}-${self:provider.stage}-save-book-to-rds
    events:
      - http:
          path: /save/{isbn}
          method: put
          cors: true
  list-books:
    handler: main.handler
    package:
      artifact: functions/artifact/list_books.zip
    description: RDSに保存されている全ての書籍情報をリストにして返す
    layers:
      - !Ref RequirementsLambdaLayer
      - !Ref MtSampleCommonLambdaLayer
    environment:
      RDS_HOST: ${self:custom.rdsHost}
      RDS_USER: ${self:custom.rdsUser}
      RDS_PASSWORD: ${self:custom.rdsPassword}
      RDS_DATABASE: ${self:custom.rdsDatabase}
    vpc:
      securityGroupIds:
        - ${self:custom.lambdaSecurityGroup}
      subnetIds:
        - ${self:custom.subnetA}
        - ${self:custom.subnetB}
    events:
      - http:
          path: /list
          method: get
          cors: true

#--------------------------------------------------------------------------------
# resources
# https://www.serverless.com/framework/docs/providers/aws/guide/resources/
#--------------------------------------------------------------------------------
resources:
  Resources:
    myDefaultRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-lambdaDefaultRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service}-${self:provider.stage}-lambdaDefaultPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:logs"
                          - !Ref AWS::Region
                          - !Ref AWS::AccountId
                          - "log-group:/aws/lambda/*:*:*"
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DeleteNetworkInterface
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                  Resource:
                    - "Fn::Join":
                        - ":"
                        - - "arn:aws:dynamodb"
                          - !Ref AWS::Region
                          - !Ref AWS::AccountId
                          - "table/*"
    parameterApiEndpoint:
      Type: AWS::SSM::Parameter
      Properties:
        Description: デプロイされたステージのAPIエンドポイント
        Type: String
        Name: /${self:service}/${self:provider.stage}/apigw/endpoint
        Value:
          "Fn::Join":
            - ""
            - - "https://"
              - !Ref ApiGatewayRestApi
              - ".execute-api."
              - ${self:provider.region}
              - ".amazonaws.com/"
              - ${self:provider.stage}
