openapi: 3.0.0
info:
  title: mt-sample-api
  version: "1.0"
  description: サンプル版（mt-sample）のAPI
paths:
  "/fetch/{isbn}":
    parameters:
      - schema:
          type: string
        name: isbn
        in: path
        required: true
        description: ISBNコード
    get:
      summary: ISBNコードから書籍情報を取得する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
              examples:
                魔法の世紀:
                  value:
                    - isbn: "9784905325055"
                      title: 魔法の世紀
                      author: 落合陽一／著
                      publisher: 株式会社PLANETS／第二次惑星開発委員会
                      cover: "https://cover.openbd.jp/9784905325055.jpg"
                書籍情報なし:
                  value:
                    -
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
              examples:
                error:
                  value: Error
  "/save-openbd/{isbn}":
    parameters:
      - schema:
          type: string
        name: isbn
        in: path
        required: true
        description: ISBNコード
    put:
      summary: OpenBD APIから取得した書籍情報を保存する
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
              examples:
                error:
                  value: Error
  "/save-gbooks/{isbn}":
    parameters:
      - schema:
          type: string
        name: isbn
        in: path
        required: true
        description: ISBNコード
    put:
      summary: GoogleBooks APIから取得した書籍情報を保存する
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
              examples:
                error:
                  value: Error
components:
  schemas:
    Book:
      description: 書籍情報
      type: object
      properties:
        isbn:
          type: string
          minLength: 13
          maxLength: 13
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        cover:
          type: string
      required:
        - isbn
        - title
