openapi: 3.0.0
info:
  title: mt-sample-api
  version: "1.0"
  description: サンプル版（mt-sample）のAPI
paths:
  "/search/{isbn}":
    parameters:
      - schema:
          type: string
        name: isbn
        in: path
        required: true
        description: ISBNコード
    get:
      summary: ISBNをもとに書籍APIから取得した書籍情報を返す
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
              examples:
                魔法の世紀:
                  value:
                    - isbn: "9784905325055"
                      title: 魔法の世紀
                      author: 落合陽一／著
                      publisher: 株式会社PLANETS／第二次惑星開発委員会
                      cover: "https://cover.openbd.jp/9784905325055.jpg"
                書籍情報なし:
                  value:
                    -
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
              examples:
                error:
                  value: Error
  "/save":
    put:
      summary: 書籍情報をRDSへ保存する
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
              examples:
                魔法の世紀:
                  value:
                    isbn: "9784905325055"
                    title: 魔法の世紀
                    author: 落合陽一／著
                    publisher: 株式会社PLANETS／第二次惑星開発委員会
                    cover: "https://cover.openbd.jp/9784905325055.jpg"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
              examples:
                error:
                  value: Error
  "/list":
    get:
      summary: RDSに保存されている全ての書籍情報をリストにして返す
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
              example:
                - isbn: "9784101010137"
                  title: こころ
                  author: 夏目漱石／著 小林勝／著 伊藤昇
                  publisher: 新潮社
                  cover: "https://cover.openbd.jp/9784101010137.jpg"
                - isbn: "9784480094131"
                  title: 計算機と脳
                  author: J.フォン・ノイマン
                  publisher: ""
                  cover: "http://books.google.com/books/content?id=MUfnygAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api"
                - isbn: "9784873115894"
                  title: SQLアンチパターン
                  author: ビルカーウィン
                  publisher: ""
                  cover: "http://books.google.com/books/content?id=InwjlwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api"
                - isbn: "9784905325055"
                  title: 魔法の世紀
                  author: 落合陽一／著
                  publisher: 株式会社PLANETS／第二次惑星開発委員会
                  cover: "https://cover.openbd.jp/9784905325055.jpg"

        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
              examples:
                error:
                  value: Error
components:
  schemas:
    Book:
      description: 書籍情報
      type: object
      properties:
        isbn:
          type: string
          minLength: 13
          maxLength: 13
        title:
          type: string
        author:
          type: string
        publisher:
          type: string
        cover:
          type: string
      required:
        - isbn
        - title
